export type MarkerReviewStatus = 'pending' | 'approved' | 'rejected';

export type BuildingConnectionMeta = {
  targetBuildingCode: string;
  role: 'entrance' | 'exit';
};

export function parseMarkerMetadata(raw: unknown): Record<string, unknown> {
  if (!raw || typeof raw !== 'object') return {};
  return { ...(raw as Record<string, unknown>) };
}

export function getMarkerReviewStatus(metadata: unknown): MarkerReviewStatus {
  const meta = parseMarkerMetadata(metadata);
  const status = meta.reviewStatus;
  if (status === 'approved' || status === 'rejected' || status === 'pending') return status;
  if (meta.autoGenerated === true) return 'pending';
  return 'approved';
}

/** Student-facing routes use approved markers only (manual markers default to approved). */
export function isMarkerVisibleToStudents(metadata: unknown): boolean {
  return getMarkerReviewStatus(metadata) === 'approved';
}

export function withReviewStatus(
  metadata: Record<string, unknown> | null | undefined,
  reviewStatus: MarkerReviewStatus
): Record<string, unknown> {
  return { ...parseMarkerMetadata(metadata), reviewStatus };
}

export function withBuildingConnection(
  metadata: Record<string, unknown> | null | undefined,
  connection: BuildingConnectionMeta
): Record<string, unknown> {
  return {
    ...parseMarkerMetadata(metadata),
    buildingConnection: connection,
    reviewStatus: 'pending' as const,
  };
}

const DOOR_LABEL = /^door\s*\d+/i;
const CORRIDOR_LABEL = /^corridor\s*(node|hub|\(auto\)|spine)/i;
const DIRECTION_PHRASE =
  /^(walk|pass|proceed|move\s+toward|enter\s+through|head\s+toward|continue|turn\s+|the\s+next\s+|the\s+cafeteria\s+occupies|the\s+lift\s+is|the\s+staircase\s+is|the\s+electrical\s+room\s+is|the\s+elv\s+room\s+is|the\s+meeting\s+room\s+is|the\s+toilets?\s+are|security\s+room\s+is\s+the\s+first)/i;

/** Old story/notes sync, door heuristics, and direction sentences - not floor-plan places. */
export function isJunkMarker(label: string, metadata: unknown): boolean {
  const meta = parseMarkerMetadata(metadata);
  if (meta.buildingConnection) return false;
  if (meta.source === 'navigation-guide') return true;
  if (meta.role === 'door' || meta.role === 'corridor') return true;
  if (DOOR_LABEL.test(label.trim())) return true;
  if (CORRIDOR_LABEL.test(label.trim())) return true;
  if (DIRECTION_PHRASE.test(label.trim())) return true;
  return false;
}

const FACILITY_LABEL = /^(STAIRCASE|STAIRS?|LIFT|ELEVATOR|TOILET|TOILETS?|WC)$/i;

/** Shown in admin: legend rooms, facilities, entrances/exits, building links. */
export function isFloorPlanPlace(label: string, type: string, metadata: unknown): boolean {
  if (isJunkMarker(label, metadata)) return false;
  const meta = parseMarkerMetadata(metadata);
  if (meta.buildingConnection) return true;
  if (
    type === 'ENTRANCE' ||
    type === 'EXIT' ||
    type === 'STAIRS' ||
    type === 'LIFT' ||
    type === 'STAIRS_LIFT' ||
    type === 'TOILET'
  ) {
    return true;
  }
  if (FACILITY_LABEL.test(label.trim())) return true;
  if (meta.role === 'symbol' && /stair|lift|toilet/i.test(label)) return true;
  if (meta.legendNumber != null) return true;
  if (meta.source === 'legend-index') return true;
  if (meta.autoGenerated === true && meta.source === 'floorplan-vision') return true;
  return /\b(ROOM|LOBBY|LAB|OFFICE|HALL|CAFETERIA|DIRECTOR|GUIDANCE|STORE|REPAIR|ENTRANCE|RECEPTION)\b/i.test(
    label
  );
}

export function getLegendNumber(metadata: unknown): number | null {
  const meta = parseMarkerMetadata(metadata);
  if (typeof meta.legendNumber === 'number') return meta.legendNumber;
  const m = String(meta.rawText || '').match(/^(\d{1,2})\s*[\.\):\-]/);
  return m ? parseInt(m[1], 10) : null;
}
