/**
 * Manual lecturer directory — names and codes you provided in chat.
 * Short code rule: first letter of first name + first letter of last name (LK, NP, SP).
 *
 * Also includes FCT DCSE/DSE/DAC staff used in LECSTU (chatbot, NLP, demos).
 * Edit this file when you add or correct lecturer details.
 */

import type { FctLecturerRosterEntry } from './fct-lecturer-roster';

const FCT_BUILDING = 'Faculty of Computing and Technology, University of Kelaniya';

/** Names and timetable codes you gave explicitly */
export const USER_PROVIDED_LECTURERS: FctLecturerRosterEntry[] = [
  {
    firstName: 'Lahiru',
    lastName: 'Kumara',
    email: 'lahiru.kumara@kln.ac.lk',
    phone: '+94 11 290 3392',
    designation: 'Senior Lecturer (Grade I)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'LK',
    office: { roomNumber: 'CS-201', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Nimal',
    lastName: 'Perera',
    email: 'nimal.perera@kln.ac.lk',
    phone: '+94 11 290 3393',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'NP',
    office: { roomNumber: 'CS-202', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Shaji',
    lastName: 'Piraba',
    email: 'lecturer@kln.ac.lk',
    phone: '+94 11 290 3394',
    designation: 'Senior Lecturer',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'SP',
    office: { roomNumber: 'CT-105', building: FCT_BUILDING, floor: 1 },
  },
];

/** Department of Software Engineering (DSE) — full staff list you provided. LECSTU dept: CT */
export const DSE_SOFTWARE_ENGINEERING_STAFF: FctLecturerRosterEntry[] = [
  {
    firstName: 'S. P.',
    lastName: 'Kasthuri Arachchi',
    email: 'sandelik@kln.ac.lk',
    designation: 'Head of the Department (DSE)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'SK',
    office: { roomNumber: 'DSE Head Office', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Sidath',
    lastName: 'Liyanage',
    email: 'sidath@kln.ac.lk',
    designation: 'Professor in Computer Science',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'SL',
    sourceUrl: 'https://fct.kln.ac.lk/dse-lecturers/prof-sidath-liyanage',
    office: { roomNumber: 'LB-CMP-03-1', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Carmel',
    lastName: 'Wijegunasekara',
    email: 'carmel@kln.ac.lk',
    designation: 'Senior Lecturer (Grade I)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'CW',
    sourceUrl: 'https://fct.kln.ac.lk/dse-lecturers/dr-carmel-wijegunasekara',
    office: { roomNumber: 'LB-CMP-03-2', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Mohamed Ishan',
    lastName: 'Sabar',
    email: 'ishans@kln.ac.lk',
    designation: 'Senior Lecturer (Grade I)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'MIS',
    office: { roomNumber: 'LB-CMP-03-3', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Muditha',
    lastName: 'Tissera',
    email: 'mudithat@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'MT',
    sourceUrl: 'https://fct.kln.ac.lk/dse-lecturers/dr-muditha-tissera',
    office: { roomNumber: 'LB-CMP-03-4', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Sandaruwan',
    lastName: 'Cooray',
    email: 'neilc@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'SC',
    office: { roomNumber: 'LB-CMP-03-5', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Hansi',
    lastName: 'Udapola',
    email: 'hansi@kln.ac.lk',
    designation: 'Lecturer (Probationary) (On study leave)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'HU',
    office: { roomNumber: 'LB-CMP-03-6', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Darsha',
    lastName: 'Jayamini',
    email: 'darshaj@kln.ac.lk',
    designation: 'Lecturer (Probationary) (On study leave)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'DJ',
    office: { roomNumber: 'LB-CMP-03-7', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Kesavan',
    lastName: 'Selvarajah',
    email: 'kesavans@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'KS',
    office: { roomNumber: 'LB-CMP-03-8', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Subodha',
    lastName: 'Rathnayake',
    email: 'subodhar@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'SR',
    office: { roomNumber: 'LB-CMP-03-9', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'M. H.',
    lastName: 'Burhanuddeen',
    email: 'mhbur231@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'BM',
    office: { roomNumber: 'LB-CMP-03-10', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Vishmila',
    lastName: 'Mahaliyanaarachchi',
    email: 'vishmilam@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'VM',
    office: { roomNumber: 'LB-CMP-03-11', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Prathyunman',
    lastName: 'Sathiabalan',
    email: 'sprath251@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'PT',
    office: { roomNumber: 'LB-CMP-03-12', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Shanilka',
    lastName: 'Haturusinghe',
    email: 'shatur251@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'SH',
    office: { roomNumber: 'LB-CMP-03-13', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'S. K. M. S.',
    lastName: 'Silva',
    email: 'skmssi251@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'MS',
    office: { roomNumber: 'LB-CMP-03-14', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Kanthathasan',
    lastName: 'Harish',
    email: 'kharish251@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'KH',
    office: { roomNumber: 'LB-CMP-03-15', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Piyumi',
    lastName: 'Dissanayake',
    email: 'kwipd231@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'PD',
    office: { roomNumber: 'LB-CMP-03-16', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'S. S.',
    lastName: 'Gunawardhana',
    email: 'ssgun241@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'SG',
    office: { roomNumber: 'LB-CMP-03-17', building: FCT_BUILDING, floor: 2 },
  },
  // No email on your list: K. M. P. Nimanga, M. V. N. D. T. Vithana, A. K. N. Duminda,
  // A. L. P. Arachchige, T. A. D. C. U. Karunathilaka, E. G. D. Chamika
];

/** Department of Computer Systems Engineering (DCSE) — full staff list you provided. LECSTU dept: CS */
export const DCSE_COMPUTER_SYSTEMS_STAFF: FctLecturerRosterEntry[] = [
  {
    firstName: 'Nimal',
    lastName: 'Dias',
    email: 'ngjdias@kln.ac.lk',
    designation: 'Head of the Department (DCSE) / Senior Professor',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'ND',
    sourceUrl: 'https://fct.kln.ac.lk/dcse-lecturers/prof-dias',
    office: { roomNumber: 'DCSE Head Office', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'H. D.',
    lastName: 'Weerasinghe',
    email: 'hesiri@kln.ac.lk',
    designation: 'Dean of the Faculty',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'HW',
    sourceUrl: 'https://fct.kln.ac.lk/dcse-lecturers/prof-dhammika-weerasinghe',
    office: { roomNumber: 'Dean Office', building: FCT_BUILDING, floor: 3 },
  },
  {
    firstName: 'Rajitha',
    lastName: 'Tennekoon',
    email: 'rajithat@kln.ac.lk',
    designation: 'Senior Lecturer (Grade I)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'RT',
    sourceUrl: 'https://fct.kln.ac.lk/dcse-lecturers/dr-rajitha-tennekoon',
    office: { roomNumber: 'LB-CMP-02-1', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Rasika',
    lastName: 'Rajapaksha',
    email: 'rasikar@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'RR',
    sourceUrl: 'https://fct.kln.ac.lk/dcse-lecturers/dr-rasika-rajapaksha',
    office: { roomNumber: 'LB-CMP-02-2', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Madusha',
    lastName: 'Chandrasena',
    email: 'madushac@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'MC',
    sourceUrl: 'https://fct.kln.ac.lk/dcse-lecturers/dr-madusha-chandrasena',
    office: { roomNumber: 'LB-CMP-02-3', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Manusha',
    lastName: 'Lakmali',
    email: 'lakmalim@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'ML',
    office: { roomNumber: 'LB-CMP-02-4', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Mekhala',
    lastName: 'Hakmanage',
    email: 'navodim@kln.ac.lk',
    designation: 'Lecturer (Unconfirmed)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'MH',
    sourceUrl: 'https://fct.kln.ac.lk/dcse-lecturers/dr-navodi-hakmanage',
    office: { roomNumber: 'LB-CMP-02-5', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Nisal',
    lastName: 'Manisha',
    email: 'nisal@kln.ac.lk',
    designation: 'Lecturer (Probationary) (On study leave)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'NM',
    office: { roomNumber: 'LB-CMP-02-6', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Pathum',
    lastName: 'Mihiranga',
    email: 'pathum@kln.ac.lk',
    designation: 'Lecturer (Probationary) (On study leave)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'PM',
    office: { roomNumber: 'LB-CMP-02-7', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Yashodhara',
    lastName: 'P. H. A. H. K.',
    email: 'yashodharah@kln.ac.lk',
    designation: 'Lecturer (Probationary) (On study leave)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'YA',
    office: { roomNumber: 'LB-CMP-02-8', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Akash Tharuka',
    lastName: 'Perera',
    email: 'akasht@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'AP',
    office: { roomNumber: 'LB-CMP-02-9', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Hirushi',
    lastName: 'Nawanjana',
    email: 'hirushin@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'HN',
    office: { roomNumber: 'LB-CMP-02-10', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Vihan',
    lastName: 'Perera',
    email: 'vihanm@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'VP',
    office: { roomNumber: 'LB-CMP-02-11', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Madhushka',
    lastName: 'Piyumal',
    email: 'madhushkak@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'MP',
    office: { roomNumber: 'LB-CMP-02-12', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Meesha',
    lastName: 'Mervyn',
    email: 'meesham@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'MM',
    office: { roomNumber: 'LB-CMP-02-13', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Hashini',
    lastName: 'Vindya',
    email: 'aahvat251@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'HV',
    office: { roomNumber: 'LB-CMP-02-14', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'J. A. R. M.',
    lastName: 'Perera',
    email: 'malsharashini96@gmail.com',
    designation: 'Temporary Lecturer',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'JP',
    office: { roomNumber: 'LB-CMP-02-15', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'I. P. S. M.',
    lastName: 'Ilankoon',
    email: 'ipsmi231@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'II',
    office: { roomNumber: 'LB-CMP-02-16', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'K. H. K.',
    lastName: 'Nimansa',
    email: 'khkni241@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'KN',
    office: { roomNumber: 'LB-CMP-02-17', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Samoshi',
    lastName: 'Shanika',
    email: 'agssh231@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'AG',
    office: { roomNumber: 'LB-CMP-02-18', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'W. L. T.',
    lastName: 'Sankalpani',
    email: 'wltsan251@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'WS',
    office: { roomNumber: 'LB-CMP-02-19', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Karunarathna',
    lastName: 'K. P. M. S. B.',
    email: 'kpmsbk261@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'KK',
    office: { roomNumber: 'LB-CMP-02-20', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Laksarani',
    lastName: 'Panduwawala',
    email: 'pklpan251@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'LP',
    office: { roomNumber: 'LB-CMP-02-21', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Shehani',
    lastName: 'Fernando',
    email: 'whskf241@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'SF',
    office: { roomNumber: 'LB-CMP-02-22', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Vishmika',
    lastName: 'Perera',
    email: 'jkvsp241@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'VI',
    office: { roomNumber: 'LB-CMP-02-23', building: FCT_BUILDING, floor: 2 },
  },
  // No email on your list: M. P. D. S. Pathirana (Temporary Demonstrator)
];

/** @deprecated Use department-specific arrays above */
export const FCT_FACULTY_LECTURERS: FctLecturerRosterEntry[] = [];

/**
 * Department of Applied Computing (DAC) — full staff list you provided.
 * Mapped to LECSTU department code CS.
 */
export const DAC_APPLIED_COMPUTING_STAFF: FctLecturerRosterEntry[] = [
  {
    firstName: 'Laalitha',
    lastName: 'Liyanage',
    email: 'laalitha@kln.ac.lk',
    designation: 'Head of the Department (DAC)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'LL',
    sourceUrl: 'https://fct.kln.ac.lk/dac-lecturers/dr-lalitha-liyanage',
    office: { roomNumber: 'DAC Head Office', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Chamli',
    lastName: 'Pushpakumara',
    email: 'chamli@kln.ac.lk',
    designation: 'Senior Lecturer (Grade I)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'CP',
    office: { roomNumber: 'LB-CMP-01-1', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Pradeep',
    lastName: 'Samarasekere',
    email: 'pradeeps@kln.ac.lk',
    designation: 'Senior Lecturer (Grade I)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'PS',
    sourceUrl: 'https://fct.kln.ac.lk/dac-lecturers/dr-pradeep-samarasekere',
    office: { roomNumber: 'LB-CMP-01-2', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Kasun',
    lastName: 'Fernando',
    email: 'kasunf@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'KF',
    office: { roomNumber: 'LB-CMP-01-3', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Chanaka',
    lastName: 'Udayanga',
    email: 'chanakau@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'CU',
    office: { roomNumber: 'LB-CMP-01-4', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Shakila',
    lastName: 'Pathirana',
    email: 'shakilap@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'SHP',
    sourceUrl: 'https://fct.kln.ac.lk/dac-lecturers/dr-shakila-pathirana',
    office: { roomNumber: 'LB-CMP-01-5', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Amila',
    lastName: 'Jeewandara',
    email: 'amilaj@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'AJ',
    office: { roomNumber: 'LB-CMP-01-6', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Induni',
    lastName: 'Siriwardene',
    email: 'induni@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'IS',
    office: { roomNumber: 'LB-CMP-01-7', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Tharaga',
    lastName: 'Sharmilan',
    email: 'tharagas@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'TS',
    office: { roomNumber: 'LB-CMP-01-8', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Shakya',
    lastName: 'Bandara',
    email: 'shakya@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'SYB',
    sourceUrl: 'https://fct.kln.ac.lk/dac-lecturers/dr-shakya-bandara',
    office: { roomNumber: 'LB-CMP-01-9', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Inoka',
    lastName: 'Peries',
    email: 'imspe231@kln.ac.lk',
    designation: 'Senior Lecturer (Grade II) (Contract basis)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'IP',
    office: { roomNumber: 'LB-CMP-01-10', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Thisara',
    lastName: 'Pathirana',
    email: 'tpath@kln.ac.lk',
    designation: 'Lecturer (Probationary) (On Study Leave)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'TP',
    office: { roomNumber: 'LB-CMP-01-11', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Rajitha',
    lastName: 'Peiris',
    email: 'rajithal@kln.ac.lk',
    designation: 'Lecturer (Probationary) (On Study Leave)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'RP',
    office: { roomNumber: 'LB-CMP-01-12', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Chamishka',
    lastName: 'Jayathilake',
    email: 'chamishkaj@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'CJ',
    office: { roomNumber: 'LB-CMP-01-13', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Chathumi',
    lastName: 'Maddumage',
    email: 'chathumis@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'CM',
    office: { roomNumber: 'LB-CMP-01-14', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Amindu',
    lastName: 'Dharmasena',
    email: 'amindud@kln.ac.lk',
    designation: 'Lecturer (Probationary)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'AD',
    office: { roomNumber: 'LB-CMP-01-15', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Chalani',
    lastName: 'Amarasinghe',
    email: 'cyama251@kln.ac.lk',
    designation: 'Lecturer (Probationary) (Contract basis)',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'CA',
    office: { roomNumber: 'LB-CMP-01-16', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Piumi',
    lastName: 'Fernando',
    email: 'wwaph241@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'PF',
    office: { roomNumber: 'LB-CMP-01-17', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Sonali',
    lastName: 'Vijayarathna',
    email: 'spvija251@kln.ac.lk',
    designation: 'Temporary Lecturer',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'SV',
    office: { roomNumber: 'LB-CMP-01-18', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Janith',
    lastName: 'Rajakaruna',
    email: 'lajraj251@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'JR',
    office: { roomNumber: 'LB-CMP-01-19', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Charith',
    lastName: 'Lakshan',
    email: 'hclaks251@kln.ac.lk',
    designation: 'Temporary Demonstrator',
    departmentCode: 'CS',
    fctDepartment: 'DAC',
    timetableCode: 'CL',
    office: { roomNumber: 'LB-CMP-01-20', building: FCT_BUILDING, floor: 1 },
  },
  // No @kln.ac.lk address on the list you pasted — add emails when available:
  // Ransika Gamage (Temporary Lecturer), Thashmila Nishadini, Tharaka Dilshan (Temporary Demonstrator)
];

/** Lecturers that appear on FET timetables under these codes (add full names when you have them) */
export const FET_TIMETABLE_CODE_LECTURERS: FctLecturerRosterEntry[] = [
  {
    firstName: 'Kasun',
    lastName: 'Vithanage',
    email: 'kasun.vithanage@kln.ac.lk',
    designation: 'Lecturer',
    departmentCode: 'CT',
    fctDepartment: 'DSE',
    timetableCode: 'KVS',
    office: { roomNumber: 'CT-110', building: FCT_BUILDING, floor: 1 },
  },
  {
    firstName: 'Manjula',
    lastName: 'Bandara',
    email: 'manjula.bandara@kln.ac.lk',
    designation: 'Lecturer',
    departmentCode: 'ET',
    fctDepartment: 'DCSE',
    timetableCode: 'MB',
    office: { roomNumber: 'ET-301', building: FCT_BUILDING, floor: 3 },
  },
  {
    firstName: 'Kanchana',
    lastName: 'Perera',
    email: 'kanchana.perera@kln.ac.lk',
    designation: 'Lecturer',
    departmentCode: 'CS',
    fctDepartment: 'DCSE',
    timetableCode: 'KP',
    office: { roomNumber: 'CS-204', building: FCT_BUILDING, floor: 2 },
  },
  {
    firstName: 'Saman',
    lastName: 'Buddhika',
    email: 'saman.buddhika@kln.ac.lk',
    designation: 'Lecturer',
    departmentCode: 'ET',
    fctDepartment: 'DSE',
    timetableCode: 'SB',
    office: { roomNumber: 'ET-302', building: FCT_BUILDING, floor: 3 },
  },
];
