export enum UserRole {
  ADMIN = 'ADMIN',
  LECTURER = 'LECTURER',
  STUDENT = 'STUDENT',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  SCHEDULED = 'SCHEDULED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  APPOINTMENT_REQUEST = 'APPOINTMENT_REQUEST',
  APPOINTMENT_ACCEPTED = 'APPOINTMENT_ACCEPTED',
  APPOINTMENT_REJECTED = 'APPOINTMENT_REJECTED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  TIMETABLE_CHANGE = 'TIMETABLE_CHANGE',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum MapMarkerType {
  ENTRANCE = 'ENTRANCE',
  EXIT = 'EXIT',
  LOBBY = 'LOBBY',
  STAIRS = 'STAIRS',
  LIFT = 'LIFT',
  PARKING = 'PARKING',
  LECTURE_HALL = 'LECTURE_HALL',
  SEMINAR_ROOM = 'SEMINAR_ROOM',
  AUDITORIUM = 'AUDITORIUM',
  CONFERENCE_ROOM = 'CONFERENCE_ROOM',
  ROOM = 'ROOM',
  HALL = 'HALL',
  LAB = 'LAB',
  WORKSHOP = 'WORKSHOP',
  LIBRARY = 'LIBRARY',
  OFFICE = 'OFFICE',
  COUNTER = 'COUNTER',
  CAFETERIA = 'CAFETERIA',
  STORE = 'STORE',
  CLINIC = 'CLINIC',
  TOILET = 'TOILET',
  PRAYER_ROOM = 'PRAYER_ROOM',
  SPORTS = 'SPORTS',
  AMENITY = 'AMENITY',
}

export interface ApiResponse<T = unknown> {
  success: boolean;
  message?: string;
  data?: T;
  errors?: Record<string, string>;
}

export interface PaginatedResponse<T> extends ApiResponse<T[]> {
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}
