import fs from 'fs';
import path from 'path';
import prisma from '../config/database';
import { config } from '../config';
import { AppError } from '../middleware/errorHandler';
import { resolveUploadFilePath } from './floorPlanStorage';
import { normalizeRoomLabelForSearch } from '../utils/floorPlanMapRegion';
import { syncNavNodesFromMarkers, createNavNode, createNavEdge } from './indoorNavigationService';
import { buildFloorNavigationGraph, clearAutoWalkingPaths } from './navGraphBuildService';
import { validateFloorNavGraph } from './navGraphValidationService';
import { Prisma, type MapMarkerType } from '../generated/prisma/client';

const VISION_META = {
  autoGenerated: true,
  source: 'floorplan-vision' as const,
  reviewStatus: 'pending' as const,
};

export type VisionPlace = {
  label: string;
  x: number;
  y: number;
  type?: 'ROOM' | 'ENTRANCE' | 'DOOR' | 'SYMBOL';
  confidence?: number;
  nearRoom?: string;
  source?: string;
  raw_text?: string;
  legendNumber?: number;
};

export type VisionAnalysis = {
  rooms: VisionPlace[];
  entrances: VisionPlace[];
  doors: VisionPlace[];
  symbols?: VisionPlace[];
  ocrCount?: number;
  engine?: string;
};

async function callVisionService(imageAbsolutePath: string): Promise<VisionAnalysis> {
  const url = `${config.floorplanVision.serviceUrl}/analyze`;
  if (!fs.existsSync(imageAbsolutePath)) {
    throw new AppError('Floor plan image file not found on disk', 404);
  }

  const buffer = fs.readFileSync(imageAbsolutePath);
  const ext = path.extname(imageAbsolutePath).toLowerCase() || '.jpg';
  const mime =
    ext === '.png' ? 'image/png' : ext === '.webp' ? 'image/webp' : 'image/jpeg';

  const form = new FormData();
  form.append('file', new Blob([buffer], { type: mime }), path.basename(imageAbsolutePath));

  const res = await fetch(url, {
    method: 'POST',
    body: form,
    signal: AbortSignal.timeout(180_000),
  });
  if (!res.ok) {
    const raw = await res.text();
    let detail = raw.slice(0, 300);
    try {
      const errJson = JSON.parse(raw) as { detail?: string };
      if (errJson.detail) detail = errJson.detail;
    } catch {
      /* use raw text */
    }
    const hint =
      res.status === 503 || res.status === 502
        ? 'Start Terminal 4: cd ai-services/floorplan-vision → .\\run_vision.ps1'
        : 'Check the floorplan-vision terminal for the error log.';
    throw new AppError(
      `Floor plan AI failed (${res.status}): ${detail || res.statusText}. ${hint}`,
      res.status >= 500 ? 502 : res.status
    );
  }

  const json = (await res.json()) as { success?: boolean; data?: VisionAnalysis };
  if (!json.success || !json.data) {
    throw new AppError('Floor plan AI returned no data', 502);
  }
  return json.data;
}

async function removeAutoGeneratedFloor(buildingId: string, floor: number) {
  const markers = await prisma.mapMarker.findMany({
    where: { buildingId, floor },
    select: { id: true, metadata: true },
  });

  const autoIds = markers
    .filter((m) => {
      const meta = m.metadata as { autoGenerated?: boolean } | null;
      return meta?.autoGenerated === true;
    })
    .map((m) => m.id);

  if (autoIds.length === 0) return;

  const navNodes = await prisma.navNode.findMany({
    where: { mapMarkerId: { in: autoIds } },
    select: { id: true },
  });
  const navIds = navNodes.map((n) => n.id);

  if (navIds.length) {
    await prisma.navEdge.deleteMany({
      where: { OR: [{ fromNodeId: { in: navIds } }, { toNodeId: { in: navIds } }] },
    });
    await prisma.navNode.deleteMany({ where: { id: { in: navIds } } });
  }

  await prisma.mapMarker.deleteMany({ where: { id: { in: autoIds } } });
}

function clampPct(v: number): number {
  return Math.max(0, Math.min(100, Number(v)));
}

async function upsertAutoMarker(
  buildingId: string,
  floor: number,
  label: string,
  x: number,
  y: number,
  type: MapMarkerType,
  extraMeta?: Record<string, unknown>
) {
  const existing = await prisma.mapMarker.findFirst({
    where: {
      buildingId,
      floor,
      label: { equals: label, mode: 'insensitive' },
    },
  });
  if (existing) {
    const meta = existing.metadata as Record<string, unknown> | null;
    if (!meta?.autoGenerated) return existing;
    return prisma.mapMarker.update({
      where: { id: existing.id },
      data: {
        x: clampPct(x),
        y: clampPct(y),
        type,
        label: normalizeRoomLabelForSearch(label) || label.trim(),
        metadata: {
          ...VISION_META,
          ...extraMeta,
          confidence: meta?.confidence,
        } as Prisma.InputJsonValue,
      },
    });
  }

  return prisma.mapMarker.create({
    data: {
      buildingId,
      floor,
      type,
      label: normalizeRoomLabelForSearch(label) || label.trim(),
      x: clampPct(x),
      y: clampPct(y),
      metadata: { ...VISION_META, ...extraMeta } as Prisma.InputJsonValue,
    },
  });
}

function markerTypeForPlace(p: VisionPlace): MapMarkerType | null {
  if (p.type === 'DOOR' || /^door\s*\d+/i.test(p.label)) return null;
  const label = p.label.trim();
  if (p.type === 'ENTRANCE' || /^(ENTRANCE|MAIN\s+ENTRANCE)/i.test(label)) return 'ENTRANCE';
  if (/^exit\b/i.test(label)) return 'EXIT';
  if (/stair/i.test(label)) return 'STAIRS';
  if (/lift|elevator/i.test(label)) return 'LIFT';
  if (/toilet|washroom|restroom|\bwc\b/i.test(label)) return 'TOILET';
  if (/cafeteria|canteen|food\s+court/i.test(label)) return 'CAFETERIA';
  if (/library/i.test(label)) return 'LIBRARY';
  if (/auditorium/i.test(label)) return 'AUDITORIUM';
  if (/seminar/i.test(label)) return 'SEMINAR_ROOM';
  if (/conference/i.test(label)) return 'CONFERENCE_ROOM';
  if (/lecture\s+hall/i.test(label)) return 'LECTURE_HALL';
  if (/workshop/i.test(label)) return 'WORKSHOP';
  if (/prayer|mosque|chapel/i.test(label)) return 'PRAYER_ROOM';
  if (/clinic|medical|dispensary/i.test(label)) return 'CLINIC';
  if (/parking/i.test(label)) return 'PARKING';
  if (/gym|sports/i.test(label)) return 'SPORTS';
  if (/store|supplies/i.test(label)) return 'STORE';
  if (/entrance\s+lobby|main\s+lobby|waiting\s+(lobby|area)/i.test(label)) {
    return /reception|counter|shroff/i.test(label) ? 'COUNTER' : 'LOBBY';
  }
  if (/\blab\b/i.test(label) && !/store|repair/i.test(label)) return 'LAB';
  if (/director|office|affairs|security|shroff/i.test(label)) {
    return /shroff|counter|reception/i.test(label) ? 'COUNTER' : 'OFFICE';
  }
  if (
    /changing\s+room|staff\s+room|store\s+room|\broom\b/i.test(label) &&
    !/restroom|washroom|prayer|lecture|seminar|conference|classroom/i.test(label)
  ) {
    return 'ROOM';
  }
  if (/hall|cafeteria/i.test(label)) return /lecture/i.test(label) ? 'LECTURE_HALL' : 'HALL';
  return 'AMENITY';
}

function metaForPlace(p: VisionPlace): Record<string, unknown> {
  const meta: Record<string, unknown> = {
    confidence: p.confidence,
    source: p.source || 'floorplan-vision',
  };
  if (p.nearRoom) meta.nearRoom = p.nearRoom;
  if (/stair/i.test(p.label)) meta.role = 'symbol';
  else if (/lift|elevator/i.test(p.label)) meta.role = 'symbol';
  else if (/toilet/i.test(p.label)) meta.role = 'symbol';
  const raw = (p as { raw_text?: string }).raw_text;
  if (raw) meta.rawText = raw;
  const numMatch = String(raw || p.label).match(/^(\d{1,2})\s*[\.\):\-]/);
  if (typeof p.legendNumber === 'number') meta.legendNumber = p.legendNumber;
  else if (numMatch) meta.legendNumber = parseInt(numMatch[1], 10);
  return meta;
}

export async function clearAutoCorridorNodes(buildingId: string, floor: number) {
  const corridors = await prisma.navNode.findMany({
    where: {
      buildingId,
      floor,
      type: 'CORRIDOR',
      OR: [
        { label: { startsWith: 'Corridor (auto)' } },
        { label: { startsWith: 'Corridor spine' } },
      ],
    },
    select: { id: true },
  });
  const ids = corridors.map((c) => c.id);
  if (!ids.length) return;
  await prisma.navEdge.deleteMany({
    where: { OR: [{ fromNodeId: { in: ids } }, { toNodeId: { in: ids } }] },
  });
  await prisma.navNode.deleteMany({ where: { id: { in: ids } } });
}

/** Corridor spine graph: lobby (right) → corridors → rooms. No diagonal shortcuts. */
export async function buildCorridorSpineGraph(
  buildingId: string,
  floor: number,
  drawableRegion?: unknown
) {
  const { displayToStorageCoord, parseDrawableRegion, CORRIDOR_SPINE_DISPLAY } = await import(
    '../utils/floorPlanMapRegion'
  );
  const region = parseDrawableRegion(drawableRegion);

  await syncNavNodesFromMarkers(buildingId, floor);
  await clearAutoCorridorNodes(buildingId, floor);

  const spineNodeIds: string[] = [];
  for (let i = 0; i < CORRIDOR_SPINE_DISPLAY.length; i++) {
    const wp = CORRIDOR_SPINE_DISPLAY[i];
    const pos = displayToStorageCoord(wp.x, wp.y, region);
    const node = await createNavNode({
      buildingId,
      floor,
      label: `Corridor spine ${wp.label}`,
      x: pos.x,
      y: pos.y,
      type: 'CORRIDOR',
    });
    spineNodeIds.push(node.id);
  }

  const connect = async (fromId: string, toId: string) => {
    if (fromId === toId) return;
    try {
      await createNavEdge({ fromNodeId: fromId, toNodeId: toId, bidirectional: true });
    } catch (err: unknown) {
      const msg = (err as { message?: string })?.message || '';
      if (!msg.includes('already exists')) throw err;
    }
  };

  for (let i = 0; i < spineNodeIds.length - 1; i++) {
    await connect(spineNodeIds[i], spineNodeIds[i + 1]);
  }

  const allNodes = await prisma.navNode.findMany({
    where: { buildingId, floor },
    select: { id: true, type: true, x: true, y: true, label: true },
  });

  const entrance = allNodes.find((n) => n.type === 'ENTRANCE');
  if (entrance && spineNodeIds[0]) {
    await connect(entrance.id, spineNodeIds[0]);
  }

  const spineNodes = allNodes.filter((n) => spineNodeIds.includes(n.id));
  const roomNodes = allNodes.filter((n) => n.type === 'ROOM');

  for (const room of roomNodes) {
    let nearest = spineNodes[0];
    let best = Infinity;
    for (const spine of spineNodes) {
      const d = Math.hypot(room.x - spine.x, room.y - spine.y);
      if (d < best) {
        best = d;
        nearest = spine;
      }
    }
    if (nearest) await connect(nearest.id, room.id);
  }

  return { spineNodes: spineNodeIds.length, rooms: roomNodes.length };
}

/** Connect entrance → hub corridor → every room (guaranteed path for chatbot) */
export async function buildAutoNavigationGraph(buildingId: string, floor: number) {
  await syncNavNodesFromMarkers(buildingId, floor);
  await clearAutoCorridorNodes(buildingId, floor);

  const nodes = await prisma.navNode.findMany({
    where: { buildingId, floor },
    select: { id: true, type: true, x: true, y: true, label: true, mapMarkerId: true },
  });

  let entrance = nodes.find((n) => n.type === 'ENTRANCE');
  if (!entrance) {
    const { displayToStorageCoord, ENTRANCE_DISPLAY_POSITION, parseDrawableRegion } = await import(
      '../utils/floorPlanMapRegion'
    );
    const plan = await prisma.floorPlan.findUnique({
      where: { buildingId_floor: { buildingId, floor } },
      select: { drawableRegion: true },
    });
    const pos = displayToStorageCoord(
      ENTRANCE_DISPLAY_POSITION.x,
      ENTRANCE_DISPLAY_POSITION.y,
      parseDrawableRegion(plan?.drawableRegion)
    );
    entrance = await createNavNode({
      buildingId,
      floor,
      label: 'Main lobby',
      x: pos.x,
      y: pos.y,
      type: 'ENTRANCE',
    });
  }

  const allNodes = await prisma.navNode.findMany({
    where: { buildingId, floor },
    select: { id: true, type: true, x: true, y: true, label: true, mapMarkerId: true },
  });

  const attachNodes = allNodes.filter(
    (n) => n.id !== entrance.id && n.type !== 'CORRIDOR'
  );

  if (attachNodes.length === 0) {
    return { corridors: 0, edges: 0, rooms: 0 };
  }

  let edgesCreated = 0;
  const connect = async (fromId: string, toId: string) => {
    if (fromId === toId) return;
    try {
      await createNavEdge({ fromNodeId: fromId, toNodeId: toId, bidirectional: true });
      edgesCreated++;
    } catch (err: unknown) {
      const msg = (err as { message?: string })?.message || '';
      if (!msg.includes('already exists')) throw err;
    }
  };

  const cx = attachNodes.reduce((s, r) => s + r.x, 0) / attachNodes.length;
  const cy = attachNodes.reduce((s, r) => s + r.y, 0) / attachNodes.length;

  const hub = await createNavNode({
    buildingId,
    floor,
    label: `Corridor (auto ${formatFloorPct(cy)})`,
    x: cx,
    y: cy,
    type: 'CORRIDOR',
  });

  await connect(entrance.id, hub.id);

  const doorMarkers = await prisma.mapMarker.findMany({
    where: { buildingId, floor },
    select: { id: true, label: true, x: true, y: true, metadata: true },
  });
  const doors = doorMarkers.filter((m) => {
    const meta = m.metadata as { role?: string } | null;
    return meta?.role === 'door' || /^door/i.test(m.label);
  });

  let doorsLinked = 0;
  for (const door of doors) {
    let doorNode = (await prisma.navNode.findMany({ where: { buildingId, floor } })).find(
      (n) => n.mapMarkerId === door.id
    );
    if (!doorNode) {
      await syncNavNodesFromMarkers(buildingId, floor);
      doorNode = (await prisma.navNode.findMany({ where: { buildingId, floor } })).find(
        (n) => n.mapMarkerId === door.id
      );
    }
    if (!doorNode) {
      doorNode = await createNavNode({
        buildingId,
        floor,
        label: door.label,
        x: door.x,
        y: door.y,
        type: 'CORRIDOR',
        mapMarkerId: door.id,
      });
    }
    await connect(hub.id, doorNode.id);
    doorsLinked++;

    const roomTargets = attachNodes.filter((n) => n.type === 'ROOM');
    let nearestRoom = roomTargets[0];
    let best = Infinity;
    for (const room of roomTargets) {
      const d = Math.hypot(door.x - room.x, door.y - room.y);
      if (d < best) {
        best = d;
        nearestRoom = room;
      }
    }
    if (nearestRoom && best < 18) {
      await connect(doorNode.id, nearestRoom.id);
    }
  }

  for (const node of attachNodes) {
    await connect(hub.id, node.id);
  }

  return {
    corridors: 1,
    edges: edgesCreated,
    rooms: attachNodes.filter((n) => n.type === 'ROOM').length,
    doorsLinked,
  };
}

/** Rebuild paths for a floor (e.g. after manual markers or failed route) */
export async function rebuildFloorNavigationGraph(buildingId: string, floor: number) {
  return buildFloorNavigationGraph(buildingId, floor);
}

function formatFloorPct(y: number): string {
  return `${Math.round(y)}%`;
}

/**
 * Run AI on floor plan JPG, create room/entrance markers, sync nav nodes, auto-build corridor graph.
 * Prefers the Indoor Navigation Engine (8004); falls back to floorplan-vision (8003).
 */
export async function processFloorPlanWithVision(
  buildingId: string,
  floor: number,
  imagePath: string
) {
  const building = await prisma.mapBuilding.findUnique({ where: { id: buildingId } });
  if (!building) throw new AppError('Building not found', 404);

  const { config } = await import('../config');
  let analysis: VisionAnalysis;
  let engineLabel = 'easyocr+opencv-v2';

  if (config.indoorNavigation.enabled) {
    try {
      const { processFloorMapWithEngine } = await import('./floorNavigationEngineService');
      const engineResult = await processFloorMapWithEngine(imagePath);
      const legendRooms =
        engineResult.legend_places?.length
          ? engineResult.legend_places
          : engineResult.rooms.filter(
              (r) => r.source === 'legend-index' || r.source === 'legend-map-match'
            );
      const roomSource =
        legendRooms.length > 0
          ? legendRooms
          : engineResult.rooms.filter((r) => r.source !== 'opencv_region');

      analysis = {
        rooms: roomSource.map((r) => ({
          label: r.label,
          x: r.x,
          y: r.y,
          confidence: r.confidence,
          type: (r.type as VisionPlace['type']) || 'ROOM',
          source: r.source,
          raw_text: r.raw_text,
          legendNumber: r.legendNumber,
        })),
        entrances: engineResult.entrances.map((e) => ({
          label: e.label,
          x: e.x,
          y: e.y,
          type: 'ENTRANCE' as const,
          confidence: e.confidence,
        })),
        doors: engineResult.doors.map((d) => ({
          label: d.label,
          x: d.x,
          y: d.y,
          type: 'DOOR' as const,
          confidence: d.confidence,
        })),
        symbols: engineResult.corridors.map((c) => ({
          label: c.label,
          x: c.x,
          y: c.y,
          type: 'SYMBOL' as const,
        })),
        ocrCount: engineResult.stats?.ocr_count,
        engine: engineResult.engine,
      };
      engineLabel = engineResult.engine;

      const floorPlan = await prisma.floorPlan.findUnique({
        where: { buildingId_floor: { buildingId, floor } },
      });
      if (floorPlan && engineResult.drawableRegion) {
        await prisma.floorPlan.update({
          where: { id: floorPlan.id },
          data: { drawableRegion: engineResult.drawableRegion },
        });
      }
    } catch (engineErr) {
      console.warn('[floorPlanVision] Navigation engine unavailable, using floorplan-vision:', engineErr);
      const absolutePath = resolveUploadFilePath(imagePath);
      analysis = await callVisionService(absolutePath);
      const floorPlan = await prisma.floorPlan.findUnique({
        where: { buildingId_floor: { buildingId, floor } },
      });
      const visionData = analysis as VisionAnalysis & { drawableRegion?: object };
      if (floorPlan && visionData.drawableRegion) {
        await prisma.floorPlan.update({
          where: { id: floorPlan.id },
          data: { drawableRegion: visionData.drawableRegion },
        });
      }
    }
  } else {
    const absolutePath = resolveUploadFilePath(imagePath);
    analysis = await callVisionService(absolutePath);
  }

  const { purgeFloorPlanJunkMarkers } = await import('./floorPlanReviewService');
  await purgeFloorPlanJunkMarkers(buildingId, floor);
  await removeAutoGeneratedFloor(buildingId, floor);

  await prisma.floorPlan.updateMany({
    where: { buildingId, floor },
    data: { navigationGuide: Prisma.DbNull },
  });

  const placements: VisionPlace[] = [...(analysis.entrances || []), ...(analysis.rooms || [])];

  let markersCreated = 0;
  for (const p of placements) {
    const type = markerTypeForPlace(p);
    if (!type) continue;
    const meta = metaForPlace(p);
    await upsertAutoMarker(buildingId, floor, p.label, p.x, p.y, type, meta);
    markersCreated++;
  }
  const doorsPlaced = 0;

  const navSync = await syncNavNodesFromMarkers(buildingId, floor);
  await clearAutoWalkingPaths(buildingId, floor);
  const graphValidation = await validateFloorNavGraph(buildingId, floor);

  return {
    markersCreated,
    roomsDetected: analysis.rooms?.length ?? 0,
    entrancesDetected: analysis.entrances?.length ?? 0,
    doorsDetected: analysis.doors?.length ?? 0,
    doorsPlaced,
    symbolsDetected: analysis.symbols?.length ?? 0,
    ocrCount: analysis.ocrCount,
    engine: analysis.engine || engineLabel,
    navSync,
    navigation: { manualOnly: true, message: 'Walking paths are drawn manually in Admin → Walking paths' },
    graphValidation,
    sampleLabels: placements.slice(0, 12).map((p) => p.label),
  };
}

export async function isVisionServiceHealthy(): Promise<boolean> {
  try {
    const res = await fetch(`${config.floorplanVision.serviceUrl}/health`, {
      signal: AbortSignal.timeout(3000),
    });
    return res.ok;
  } catch {
    return false;
  }
}
